# Generated by Django 5.0.3 on 2024-04-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_video', models.CharField(max_length=100)),
                ('path_model', models.CharField(max_length=100)),
            ],
        ),
    ]
